# Generated by Django 4.0 on 2024-02-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='text',
            new_name='message',
        ),
    ]
